insert into DEPARTMENT( DEPARTMENT_NAME, MANAGER_ID) values ('ADMIN',null);
insert into DEPARTMENT( DEPARTMENT_NAME, MANAGER_ID) values ('IT',null);
insert into DEPARTMENT( DEPARTMENT_NAME, MANAGER_ID) values ('HR',null);

insert into EMPLOYEE (DEPARTMENT_ID ,EMAIL ,FIRST_NAME ,HIRE_DATE ,LAST_NAME ,MANAGER_ID ,PHONE_NUMBER ,SALARY ) values (1, 'john_doe@mayur.com', 'John', CURRENT_DATE(), 'Doe', null, '917-852-9865', 5698.2);
insert into EMPLOYEE (DEPARTMENT_ID ,EMAIL ,FIRST_NAME ,HIRE_DATE ,LAST_NAME ,MANAGER_ID ,PHONE_NUMBER ,SALARY ) values (2, 'sam_nickel@mayur.com', 'Sam', CURRENT_DATE(), 'Nickel', null, '917-456-9865', 8795.5);
insert into EMPLOYEE (DEPARTMENT_ID ,EMAIL ,FIRST_NAME ,HIRE_DATE ,LAST_NAME ,MANAGER_ID ,PHONE_NUMBER ,SALARY ) values (3, 'august_rim@mayur.com', 'August', CURRENT_DATE(), 'Rim', null, '917-789-9865', 65934.2);

update DEPARTMENT set MANAGER_ID = (select EMPLOYEE_ID from EMPLOYEE where FIRST_NAME = 'John') where DEPARTMENT_ID =(select DEPARTMENT_ID from DEPARTMENT where DEPARTMENT_NAME = 'ADMIN');
update DEPARTMENT set MANAGER_ID = (select EMPLOYEE_ID from EMPLOYEE where FIRST_NAME = 'Sam') where DEPARTMENT_ID =(select DEPARTMENT_ID from DEPARTMENT where DEPARTMENT_NAME = 'IT');
update DEPARTMENT set MANAGER_ID = (select EMPLOYEE_ID from EMPLOYEE where FIRST_NAME = 'August') where DEPARTMENT_ID =(select DEPARTMENT_ID from DEPARTMENT where DEPARTMENT_NAME = 'HR');

insert into EMPLOYEE (DEPARTMENT_ID ,EMAIL ,FIRST_NAME ,HIRE_DATE ,LAST_NAME ,MANAGER_ID ,PHONE_NUMBER ,SALARY ) values (1, 'bill_trucker@mayur.com', 'Bill', CURRENT_DATE(), 'Trucker', 1, '917-753-9865', 100.4);
insert into EMPLOYEE (DEPARTMENT_ID ,EMAIL ,FIRST_NAME ,HIRE_DATE ,LAST_NAME ,MANAGER_ID ,PHONE_NUMBER ,SALARY ) values (1, 'cassy_win@mayur.com', 'Cassy', CURRENT_DATE(), 'Win', 1, '917-754-9865', 4568.44);
insert into EMPLOYEE (DEPARTMENT_ID ,EMAIL ,FIRST_NAME ,HIRE_DATE ,LAST_NAME ,MANAGER_ID ,PHONE_NUMBER ,SALARY ) values (2, 'donald_smith@mayur.com', 'Donald', CURRENT_DATE(), 'Smith', 2, '917-865-9865', 4568.4);
insert into EMPLOYEE (DEPARTMENT_ID ,EMAIL ,FIRST_NAME ,HIRE_DATE ,LAST_NAME ,MANAGER_ID ,PHONE_NUMBER ,SALARY ) values (2, 'jack_reel@mayur.com', 'Jack', CURRENT_DATE(), 'Reel', 2, '917-958-9865', 4.56);
insert into EMPLOYEE (DEPARTMENT_ID ,EMAIL ,FIRST_NAME ,HIRE_DATE ,LAST_NAME ,MANAGER_ID ,PHONE_NUMBER ,SALARY ) values (3, 'larry_page@mayur.com', 'Larry', CURRENT_DATE(), 'Page', 3, '917-356-9865', 45678.5);
insert into EMPLOYEE (DEPARTMENT_ID ,EMAIL ,FIRST_NAME ,HIRE_DATE ,LAST_NAME ,MANAGER_ID ,PHONE_NUMBER ,SALARY ) values (3, 'mayur_song@mayur.com', 'Mayur', CURRENT_DATE(), 'Song', 3, '917-246-9865', 568);
